version: 2

jobs:
  "buildp":
    docker:
      - image: docker:17.06.1-ce-git
        #environment:
        #  ENV: $BASH_ENV
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
             apk add --no-cache bash
             apk update
             apk upgrade
             #apk add alpine-sdk
             apk add make
  
             
             git clone https://github.com/awslabs/git-secrets 
             cd git-secrets 
             make install 
             git secrets --install ~/.git-templates/git-secrets 
             git config --global init.templateDir ~/.git-templates/git-secrets 
             git secrets --register-aws --global 
             cd ..
                 
      - run:
          name: Scanning
          command: |    
             #echo "AWS_ACCOUNT_ID=811456781234" > /root/project/t1.txt
             #git secrets --scan -r $CIRCLE_WORKING_DIRECTORY
             git secrets --scan -r 
             
             
notify:
  webhooks:
    - url: https://foo.bar.com/build-webhook
experimental:
  notify:
    branches:
      only:
        - master
        - staging
        
        

workflows:
  version: 2
  build:
    jobs:
      - "buildp":
          filters:
            branches:
              only: master
